version: '3.8'

services:
  nextjs-typescript:
    ports:
      - 3000:3000
    build:
      context: ./nextjs
    volumes:
      - ./nextjs:/app

  anchor:    
    build:
      context: ./anchor
      args:
        - SOLANA_CLI=stable
        - ANCHOR_CLI=v0.25.0
    volumes:
      - ./anchor:/workdir
