[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "WJjLkThJKPff4aF9QDf8jZaYoosoMrim7dZzVqJ6QDc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
